export const ADD_NEW_CONTACT_REQUEST="ADD_NEW_CONTACT_REQUEST";
export const ADD_NEW_CONTACT_SUCCESS="ADD_NEW_CONTACT_SUCCESS";
export const ADD_NEW_CONTACT_FAIL="ADD_NEW_CONTACT_FAIL";
export const ADD_NEW_CONTACT_RESET="ADD_NEW_CONTACT_RESET";

export const GET_CONTACT_SUCCESS="GET_CONTACT_SUCCESS";
export const GET_CONTACT_REQUEST="GET_CONTACT_REQUEST";
export const GET_CONTACT_FAILED="GET_CONTACT_FAILED";

export const GET_SINGLE_CONTACT_SUCCESS="GET_SINGLE_CONTACT_SUCCESS";
export const GET_SINGLE_CONTACT_REQUEST="GET_SINGLE_CONTACT_REQUEST";
export const GET_SINGLE_CONTACT_FAILED="GET_SINGLE_CONTACT_FAILED";


export const Clear_Error="Clear_Error";